import os
print("╔══════════════════════════════════════════════════════════════════╗")
print("║                     VOX MODULES (print-only)                     ║")
print("╠══════════════════════════════════════════════════════════════════╣")
print("║ sensor.py    → discovers deepiri-* and diri-* repos             ║")
print("║ brain.py     → classifies: NODE, PYTHON, RUST, UNKNOWN           ║")
print("║ report.py    → beautiful output with types                       ║")
print("║ size.py      → calculates total file sizes                       ║")
print("║ git.py       → git status: dirty, clean, no-git                 ║")
print("║ health.py    → checks for requirements.txt / pyproject.toml      ║")
print("║ branch.py    → prints current git branch (or none)               ║")
print("║ deps.py      → counts npm dependencies or pyproject.toml lines   ║")
print("║ tests.py     → checks for test/ tests/ pytest.ini                ║")
print("║ dashboard.py → master UI combining all modules                  ║")
print("║ pipeline.py  → sequential execution with progress               ║")
print("╚══════════════════════════════════════════════════════════════════╝")
print()
print("USAGE:  cd /home/joeblack/Documents/Deepiri && python3 deepiri-vox/pipeline.py")
print("PIPE:   python3 deepiri-vox/sensor.py | python3 deepiri-vox/brain.py | python3 deepiri-vox/report.py")